// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nklzooanyyctoqowgimb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rbHpvb2FueXljdG9xb3dnaW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDM1MjAsImV4cCI6MjA2NjAxOTUyMH0.MMz8exqmL0nQ7kTqVV9Xqzh-qR0fDi5Xl3vSafNoDA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});